# -*- coding: utf-8 -*-
"""마구간 정하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m2r_jhpiTjIZmbV6xfBx4cZWJW4DHLwb
"""

#마구간 정하기(결정알고리즘)

n,k = map(int,input().split())

Line = []

def Count(len):
  cnt = 1
  ep= Line[0]
  for i in range(1,n):
    if Line[i]-ep>=len:
      cnt+=1
      ep = Line[i]
  return cnt


for _ in range(n):
    tmp = int(input())
    Line.append(tmp)

Line.sort()
lt = 1
rt = Line[n-1]

while lt <= rt:
  mid = (lt + rt )//2
  if Count(mid) >=k:
    res = mid
    lt = mid + 1
  else:
    rt = mid -1

print(res)

